dist: trusty
sudo: false
language: cpp

# branches:
#   only:
#     - master


# addons:
matrix:
  include:

  # - os: linux
  #   addons:
  #     apt:
  #       packages:
  #         - doxygen
  #         - doxygen-doc
  #         - doxygen-latex
  #         - doxygen-gui
  #         - graphviz

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
          # - valgrind
    env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - TEST_COMPILER="gcc"
    
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          # - valgrind
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      - TEST_COMPILER="gcc"

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          # - valgrind
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - TEST_COMPILER="gcc"

  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        packages:
          - clang-3.8
          # - valgrind
    env:
      - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      - TEST_COMPILER="clang"

  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          # - valgrind
    env:
      - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      - TEST_COMPILER="clang"

  # - os: linux
  #   addons:
  #     apt:
  #       sources:
  #         - llvm-toolchain-trusty-4.0
  #       packages:
  #         - clang-4.0
  #         - valgrind
  #   env:
  #     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
  #     - TEST_COMPILER="clang"

  # - os: linux
  #   addons:
  #     apt:
  #       sources:
  #         - llvm-toolchain-trusty-5.0
  #       packages:
  #         - clang-5.0
  #         - valgrind
  #   env:
  #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  #     - TEST_COMPILER="clang"


before_install:
    - eval "${MATRIX_EVAL}"


script:
    # - cd docs
    # - doxygen doxyfile
    # - cd ..
    # - cd test && ./run_tests.py -c $TEST_COMPILER --valgrind
    - cd test && ./run_tests.py -c $TEST_COMPILER 

# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: $TRAVIS_BUILD_DIR/docs/html
#   github_token: $GITHUB_API_KEY
#   on:
#     branch: master

